version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: apex-retail-store-intelligence:latest
    container_name: apex_store_intelligence_api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    restart: always
